server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: add-service
          uri: lb://add-service/
          predicates:
            - Path=/add-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: add-service
                fallbackUri: forward:/getServiceFallback

        - id: get-service
          uri: lb://get-service/
          predicates:
            - Path=/get-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: add-service
                fallbackUri: forward:/getServiceFallback
eureka:
  client:
    service-url:
      defaultZone: http://eureka:2000/eureka