server:
  port: 0

spring:
  application:
    name: add-service

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.example.microservicesender.serializers.PersonSerializer

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.example.microservicesender.serializers.PersonDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://eureka:2000/eureka

management:
  tracing:
    sampling:
      probability: 1
